version: 2.1

orbs:
  node: circleci/node@4.3.0

jobs:
  build:
    docker:
      - image: circleci/node:14.16.0
    working_directory: ~/HireUp
    steps:
      - checkout
      - run:
          name: Install Node.js and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_19.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g npm@9.6.5
      - run:
          name: Install dependencies and build
          command: |
            npm install
            npm run build