version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install:
          node-version: "16.19.1"
      - node/install-packages:
          pkg-manager: npm
      - run: npm run build