version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.16.0
    working_directory: ~/HireUp
    steps:
      - checkout
      - node/install:
          node-version: "16.19.1"
      - node/install-packages:
          pkg-manager: npm
      - run: npm install
      - run: npm run build