version: 2.1

orbs:
  node: circleci/node@4.3.0

jobs:
  build:
    docker:
      - image: circleci/node:14.16.0
    working_directory: ~/HireUp
    steps:
      - checkout
      - node/install:
          node-version: "16.19.1"
      - run:
          name: Install dependencies
          command: |
            npm install -g npm@9.6.5
            npm install
      - run:
          name: Build
          command: npm run build